logger:
  path: ./logs
  rotate_size: 100 #MB
  max_files: 100
  level: 1 #0:trace,1:debug,2:info,3:warn,4:error,5:critical,6:off

kafka_producer:
  brokers: 47.94.215.223:9092

opc:
  station_id: 1
  station_name: 邹庄煤矿
  interval: 1000
  max_thread_count: 6
  clients:
    -
      id: 1
      name: 1-4号机组
      server: opc.tcp://localhost:4840
      dist: DATA_ACQUISITION_REALTIME
      nodes: [[1,1000]]




