Logger:
  path: ./logs
  rotateSize: 100 #单位MB
  maxFiles: 100;
  level: 1 #0:trace,1:debug,2:info,3:warn,4:error,5:critical,6:off

KafkaProducer:
  brokers: 47.94.215.223:9092
  topic: DATA_ACQUISITION_REALTIME




