logger:
  path: ./logs
  rotate_size: 100 #MB
  max_files: 100
  level: 1 #0:trace,1:debug,2:info,3:warn,4:error,5:critical,6:off

kafka_producer:
  brokers: 47.94.215.223:9092

station_code: zouzhuang

opc:
  interval: 1000
  clients:
    -
      code: no1_machine
      server: opc.tcp://localhost:4840
      dist: electric_trace_test
      nodes_config: ./config/no1_machine_nodes.yml




